site_name: GFK Prüfungsvorbereitung
docs_dir: docs

nav:
  - Übersicht: Prüfungsschwerpunkte.md
  - Schwerpunkte:
    - Gründung im Handwerk: Schwerpunkte/Gründung im Handwerk.md
    - Marketing: Schwerpunkte/Marketing.md
    - Rechtsformen: Schwerpunkte/Rechtsformen.md
    - Finanzierung: Schwerpunkte/Finanzierung.md
    - Rentabilitätsvorschau: Schwerpunkte/Rentabilitätsvorschau.md
    - Personalwesen: Schwerpunkte/Personalwesen.md
    - Kommunikation: Schwerpunkte/Kommunikation.md
    - Arbeitsrecht: Schwerpunkte/Arbeitsrecht.md
    - Organisation: Schwerpunkte/Organisation.md
    - Bürgerliches Gesetzbuch: Schwerpunkte/Bürgerliches Gesetzbuch.md
    - Wirtschaftsrecht: Schwerpunkte/Wirtschaftsrecht.md
    - Steuern: Schwerpunkte/Steuern.md
    - Controlling: Schwerpunkte/Controlling.md
    - Kosten-Leistungs-Rechnung: Schwerpunkte/Kosten-Leistungs-Rechnung.md
    - Kommunikations- und Präsentationstechniken: Schwerpunkte/Kommunikations- und Präsentationstechniken.md

theme:
  name: material
  language: de
  features:
    - navigation.expand
    - search.highlight

plugins:
  - search:
      lang: de
