site_name: GFK Prüfungsvorbereitung
site_url: https://bobobass84.github.io/BB84.GFK/
docs_dir: docs

nav:
  - Handlungsfeld 1 - Wettbewerbsfähigkeit von Unternehmen beurteilen:
      - Grundlagen Rechnungswesen: "Schwerpunkte/Handlungsfeld 1/Grundlagen Rechnungswesen.md"
      - Kosten- und Leistungsrechnung: "Schwerpunkte/Handlungsfeld 1/Kosten- und Leistungsrechnung.md"
      - Marketing I: "Schwerpunkte/Handlungsfeld 1/Marketing I.md"
      - Wirtschaftsrecht: "Schwerpunkte/Handlungsfeld 1/Wirtschaftsrecht.md"
  - Handlungsfeld 2 - Gründungs- und Übernahmeaktivitäten vorbereiten, durchführen und bewerten:
      - Investitionsrechnung - Finanzierung: "Schwerpunkte/Handlungsfeld 2/Investitionsrechnung - Finanzierung.md"
      - Recht: "Schwerpunkte/Handlungsfeld 2/Recht.md"
      - Unternehmensgründung - Unternehmensübernahme: "Schwerpunkte/Handlungsfeld 2/Unternehmensgründung - Unternehmensübernahme.md"
  - Handlungsfeld 3 - Unternehmensführungsstrategien entwickeln:
      - Arbeits- und Sozialversicherungsrecht: "Schwerpunkte/Handlungsfeld 3/Arbeits- und Sozialversicherungsrecht.md"
      - Investitionsrechnung - Finanzierung: "Schwerpunkte/Handlungsfeld 3/Investitionsrechnung - Finanzierung.md"
      - Marketing II - Controlling: "Schwerpunkte/Handlungsfeld 3/Marketing II - Controlling.md"
      - Organisation: "Schwerpunkte/Handlungsfeld 3/Organisation.md"
      - Personal - Mitarbeiterführung: "Schwerpunkte/Handlungsfeld 3/Personal - Mitarbeiterführung.md"
  - Kommunikations- und Präsentationstechniken im Geschäftsverkehr einsetzen: "Schwerpunkte/Kommunikations- und Präsentationstechniken im Geschäftsverkehr einsetzen.md"

theme:
  name: material
  language: de
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Hellmodus
  features:
    - navigation.expand
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

markdown_extensions:
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: de
  - redirects:
      redirect_maps:
        "index.md": "Schwerpunkte/Handlungsfeld 1/Grundlagen Rechnungswesen.md"
  - callouts
